version: '3'
services:
  app: &app_base
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    links:
     - db
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - "MYSQL_USERNAME=root"
      - "MYSQL_PASSWORD=password"
      - "MYSQL_HOST=db"
    depends_on:
      - db
  db:
    image: mysql:5.7
    volumes:
      - datastore:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
volumes:
  datastore:
